//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public struct GameScoreDefineKeys
	{
		public const string MountainAdventure = "MA_";
		public const string CityAdventure = "CA_";
		public const string BeachAdventure = "BA_";
		public const string EndlessAdventure = "EL_";
		public const string ScoreName = "_Score";
		public const string Level = "Level_";
		public const string RequiredScore = "_Score_Required";
		public const string Total = "Total";
	}
}

