//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public struct UserAccountDefineKeys{

		public const string FBToken = "FBToken";
		public const string FBEmail = "FBEmail";
		public const string FBID = "FBID";
		public const string FBUsername = "FBUsername";
		public const string FBLoginStatus = "FBLoginStatus";
		public const string FBIsLogin = "Login";
		public const string FBIsLogout = "Logout";

		public const string UUID = "UUID";
	
		public const string TemporaryEmail = "temp@noemail.com";
		public const string TemporaryID = "00000000";
		public const string TemporaryUser = "Temp User";
		public const string TemporaryToken = "fffffff";

	}

}

