//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public struct UserDefineKeys
	{
		public string FBToken{
			get{
				return "FBToken";
			}
		}
		
		public string FBEmail{
			get{
				return "FBEmail";
			}
		}
		
		public string FBUserID{
			get{
				return "FBID";
			}
		}
		
		public string FBUsername{
			get{
				return "FBUsername";
			}
		}
		
		public string UUID{
			get{
				return "UUID";
			}
		}
		
		public string Level{
			get{
				return "Level_";
			}
		}

		public string RequiredScore{
			get{
				return "_Score_Required";
			}
		}

		public string Score{
			get{
				return "_Score";
			}
		}

		public string Total{
			get{
				return "Total";
			}
		}
	}
}

