//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

namespace AssemblyCSharp {

	public class UserAccount {
		
		protected string userEmail ="";
		protected string userId = "";
		protected string userName = "";
		protected CouchbaseDatabase couchbaseDatabase;


		#region Public Method
		public UserAccount(){

		}

		public UserAccount (CouchbaseDatabase  couchbase){

			couchbaseDatabase = couchbase;
		}

		public void SetDatabase(CouchbaseDatabase couchbase){
			couchbaseDatabase = couchbase;
		}

		public string Create(){
			return GenerateNewUUID ();
		}

		public virtual void Update(string UUID){

		}

		public virtual string GetUUID(){
			return "";
		}

		#endregion

		#region Public Properties
		public string UserName{
			set{
				userName = value;
			}
			get{
				return userName;
			}
		}

		public string UserEmail{
			set{
				userEmail = value;
			}
			get{
				return userEmail;
			}

		}

		public string UserID{
			set{
				userId = value;
			}
			get{
				return userId;
			}
		}
		
		#endregion

		#region Protected Methods
		protected virtual string GenerateNewUUID(){
			return "";
		}

		protected virtual void IDDocumentLookUp(string ID){
		}

		protected virtual void EmailDocumentLookUp(string ID){
		}
		#endregion

	}
}

