//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;

namespace AssemblyCSharp
{
	public class OnScreenLog
	{
		private static GameObject textLogObject;
		private static Text textLog;

		public static void write(string message){
			if (textLogObject == null && textLog == null) {
				textLogObject = GameObject.FindGameObjectWithTag("DebugText");

			}else {
				textLog = textLogObject.GetComponent<Text> ();
				textLog.text += message + "\n";
			}
		}
	}
}

