//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class UserAccountDataHandlerFactory
	{	
		private static UserAccountDataHandlerFactory instance;

		public static void Instance(){
			if (instance = null) {
				instance = new UserAccountDataHandlerFactory();
			}

			return instance;
		}

		public IUserAccountDataHandler GetDataHandler(SocialMediaType socialMediaType){

			switch (socialMediaType) {
				case SocialMediaType.FACEBOOK:
					return new UserAccountFacebookDataHandler();
				default:
					return null;
			}
		}

		private UserAccountDataHandlerFactory ()
		{
		}
	}
}

